dependency-names:
  # bundler
  - 'rails'
  - 'bootstrap-sass'
  - 'puma'
  - 'sass-rails'
  - 'uglifier'
  - 'coffee-rails'
  - 'jquery-rails'
  - 'turbolinks'
  - 'jbuilder'
  - 'bcrypt'
  - 'therubyracer'
  - 'faker'
  - 'carrierwave'
  - 'mini_magick'
  - 'will_paginate'
  - 'bootstrap-will_paginate'
  - 'sqlite3'
  - 'byebug'
  - 'rspec-rails'
  - 'factory_bot_rails'
  - 'spring-commands-rspec'
  - 'web-console'
  - 'listen'
  - 'spring'
  - 'spring-watcher-listen'
  - 'annotate_gem'
  - 'annotate'
  - 'solargraph'
  - 'rails-controller-testing'
  - 'minitest-reporters'
  - 'guard'
  - 'guard-minitest'
  - 'capybara'
  - 'selenium-webdriver'
  - 'pg'
  - 'fog'
  - 'tzinfo-data'
