version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  rebase-strategy: disabled
  versioning-strategy: lockfile-only
  labels:
  - "gem"
  - "dependencies"
  - "lockfile-only"
  allow:
  - dependency-type: all
