version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  rebase-strategy: disabled
  versioning-strategy: lockfile-only
