version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: hourly
    timezone: Asia/Tokyo
  rebase-strategy: disabled
  versioning-strategy: lockfile-only
  labels:
  - "gem"
  - "dependencies"
  - "lockfile-only"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: hourly
    timezone: Asia/Tokyo
  rebase-strategy: disabled
  versioning-strategy: increase
  labels:
  - "gem"
  - "dependencies"
  - "increase"
  target-branch: master
