name: Approve pull request which update dependencies
on:
  pull_request:
    types:
    - synchronize
jobs:
  approve-pull-request-which-update-dependencies:
    runs-on: ubuntu-latest
    if:
      contains(github.event.pull_request.labels.*.name, 'dependencies')
      && contains(github.event.pull_request.labels.*.name, 'approved by bot')
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DEPENDABOT_KEEP_UP_TO_DATE_APP_ID }}
          private_key: ${{ secrets.DEPENDABOT_KEEP_UP_TO_DATE_PRIVATE_KEY }}

      - name: Approve pull request
        run: gh pr review --approve -b "Because it is a pull request which update dependences" ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
