name: Approve pull request which update dependencies
on:
  pull_request:
    types:
    - labeled
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
jobs:
  approve-pull-request-which-update-dependencies:
    runs-on: ubuntu-latest
    if:
      contains(github.event.pull_request.labels.*.name, 'dependencies')
      && contains(github.event.pull_request.labels.*.name, 'approved by bot')
    steps:
      - name: Approve pull request
        run: gh pr review --approve -b "Because it is a pull request which update dependences" ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
